# https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry
# https://docs.npmjs.com/trusted-publishers#step-2-configure-your-cicd-workflow
name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Required for OIDC
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false # never use caching in release builds
      - run: npm ci
      - run: npm run build -- ion-icon-angular-standalone -c production
      - run: npm publish ./dist/ion-icon-angular-standalone
